export const POKEMON_REQUEST    = "POKEMON_REQUEST";
export const POKEMON_FAIL       = "POKEMON_FAIL";
export const POKEMON_SUCCCESS   = "POKEMON_SUCCCESS";
export const POKEMONSEARCH_FAIL   = "POKEMONSEARCH_FAIL";
export const POKEMONSEARCH_REQUEST   = "POKEMONSEARCH_REQUEST";
export const POKEMONSEARCH_SUCCCESS   = "POKEMONSEARCH_SUCCCESS";